### ISSUE TITLE
ERD 완성 및 엔티티 구성 완료 #25

### ISSUE THREAD

**Issue by sonb9615** [OhSonDoSon/BalanceGame#30]
# Feat : #25 

## Description
- DB 테이블 구성 완료

## To-Do
- [x] ERD 생성 완료 및 위키 업로드
- [x] DDL 생성 및 위키 업로드
- [x] entity 구성 완료
