### ISSUE TITLE
set: github-actions 설정 - #2

### ISSUE THREAD

**Issue by OhDaky** [OhSonDoSon/BalanceGame#8]
# set: github-actions 설정 - #2 

## Description
- 프론트엔드 CI/CD를 위한 github actions 설정

## To-Do
- [x] 코드 포맷팅 및 린팅 : ESLint & Prettier 설정
- [x] Docker 이미지 빌드 및 푸시
- [ ] Storybook 문서 자동 생성
- [ ] 테스트 자동화 w.Jest

## ETC
- Jest 를 이용한 테스트 자동화는 코드 개발 추후에

**Comment by OhDaky** [comment]
~ 테스트 코드 작성 후 다시 오픈하겠습니다 ~
